-- Adds the wish_requests / wish_comments tables backing the new
-- WishRequests / WishComments Payload collections (src/collections/
-- WishRequests.ts, WishComments.ts -- the real /wishbasket clone, C1).
--
-- Hand-written, not generated by `payload migrate:create`: that command
-- currently crashes on this machine's Node 24.19.0
-- (ERR_REQUIRE_ASYNC_MODULE, an ESM/CJS incompatibility in Payload's CLI
-- loader, unrelated to this project's own code -- see COLLAB.md). With
-- postgresAdapter({ push: false }) (src/payload.config.ts), Payload does
-- not auto-create tables for new collections at boot, so without this
-- migration every query against the new collections fails with
-- "relation does not exist".
--
-- Column/index/FK naming matches the existing donation_pledges and
-- bookings tables exactly (Payload's own Drizzle-generated convention),
-- reproduced by inspecting `\d donation_pledges` / `\d bookings` /
-- `\d payload_locked_documents_rels` first so this migration lands on
-- schema Payload will recognize without any drift.
--
-- Safe / additive only: creates two new tables and adds two new
-- (nullable) columns to payload_locked_documents_rels. Nothing existing
-- is altered or dropped.

BEGIN;

CREATE TYPE "public"."enum_wish_requests_status" AS ENUM ('pending', 'approved', 'fulfilled', 'rejected');

CREATE TABLE "wish_requests" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar NOT NULL,
	"shown_name" varchar,
	"email" varchar NOT NULL,
	"library_card" varchar NOT NULL,
	"writer" varchar NOT NULL,
	"title" varchar NOT NULL,
	"comment" varchar,
	"status" "public"."enum_wish_requests_status" DEFAULT 'pending' NOT NULL,
	"admin_note" varchar,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE INDEX "wish_requests_created_at_idx" ON "wish_requests" USING btree ("created_at");
CREATE INDEX "wish_requests_updated_at_idx" ON "wish_requests" USING btree ("updated_at");

CREATE TYPE "public"."enum_wish_comments_status" AS ENUM ('pending', 'approved', 'rejected');

CREATE TABLE "wish_comments" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar NOT NULL,
	"shown_name" varchar,
	"email" varchar NOT NULL,
	"comment" varchar NOT NULL,
	"status" "public"."enum_wish_comments_status" DEFAULT 'pending' NOT NULL,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE INDEX "wish_comments_created_at_idx" ON "wish_comments" USING btree ("created_at");
CREATE INDEX "wish_comments_updated_at_idx" ON "wish_comments" USING btree ("updated_at");

ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "wish_requests_id" integer;
ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "wish_comments_id" integer;

ALTER TABLE "payload_locked_documents_rels"
	ADD CONSTRAINT "payload_locked_documents_rels_wish_requests_fk"
	FOREIGN KEY ("wish_requests_id") REFERENCES "public"."wish_requests"("id") ON DELETE CASCADE;

ALTER TABLE "payload_locked_documents_rels"
	ADD CONSTRAINT "payload_locked_documents_rels_wish_comments_fk"
	FOREIGN KEY ("wish_comments_id") REFERENCES "public"."wish_comments"("id") ON DELETE CASCADE;

CREATE INDEX "payload_locked_documents_rels_wish_requests_id_idx" ON "payload_locked_documents_rels" USING btree ("wish_requests_id");
CREATE INDEX "payload_locked_documents_rels_wish_comments_id_idx" ON "payload_locked_documents_rels" USING btree ("wish_comments_id");

COMMIT;
